### ISSUE TITLE
OG and Twitter Tags

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#10]
Each route should include OG tags and Twitter tags in the page header so that they sites like Facebook and Twitter can generate previews of our content.

We should test that the previews are working correctly at:
https://cards-dev.twitter.com/validator
and
https://developers.facebook.com/tools/debug/

**Fallback**
Any page that doesn't have other tags specified should use these.
```
// OG Tags
<meta property="og:title" content="Burn Signal" />
<meta property="og:description" content="Got an opinion? Burn ETH to prove it." />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://burnsignal.io" />
<meta property="og:image" content="{Burn Signal logo URL}" />

// Twitter Tags
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@burnsignal" />
<meta name="twitter:title" content="Burn Signal" />
<meta name="twitter:description" content="Got an opinion? Burn ETH to prove it." />
<meta name="twitter:image" content="{Burn Signal logo URL}" />
```

**Polls**
All polls should generate page specific tags as follows.
```
// OG Tags
<meta property="og:title" content="{Poll Title}" />
<meta property="og:description" content="{Poll Description}" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://burnsignal.io" />
<meta property="og:image" content="{Burn Signal logo URL}" />

// Twitter Tags
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@burnsignal" />
<meta name="twitter:title" content="{Poll Title}" />
<meta name="twitter:description" content="{Poll Description}" />
<meta name="twitter:image" content="{Burn Signal logo URL}" />
```

**Comment by samgos** [comment]
Addressed in https://github.com/burnsignal/burnsignal/commit/d56573ad92442de3545d783e441e7a67e7b8b518, due to the dynamically and scripted nature of poll page metatags, they can not be parsed. This should be a feature implemented in the MVP given more research towards a suitable implementation.
