### ISSUE TITLE
Add skeleton loading elements

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#12]
It often takes the app 30 seconds or more to load the first time.
We should add some skeleton loader elements to the page so that users know to sit tight and wait for it to load.

🌮 make the skeleton loaders entertaining, think Discord's loading messages.
🌮 decrease the loading times!

**Comment by stygian-96** [comment]
Hey!! I want to work on this.
Can you guide me?

**Comment by nitin094-hub** [comment]
@auryn-macmillan can you plz suggest how to use this project as I am really interested in contributing to it.

**Comment by auryn-macmillan** [comment]
Thanks for the interest, @nitin094-hub.
This project is on a bit of a hiatus, as it ran into some significant hurdles with the increase in gas prices.
It will more than likely be superseded by [Poster](https://github.com/ETHPoster/contract) and/or [Snapshot](https://snapshot.org/). So I'd recommend contributing to either of those two projects for the time being.
