### ISSUE TITLE
Update the UI when new data is available

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#15]
Whenever a new poll is created or a new vote cast, the UI should automatically update without the user needing to refresh.

Also, immediately after creating a new poll or submitting a new vote, the users interface should optimistically display the changes (perhaps in a pending state) until the transaction is confirmed or rejected.

**Comment by samgos** [comment]
Addressed in https://github.com/burnsignal/burnsignal/commit/d3593b6704a0acfa4fec8796410ce2da1fad3eb0.
