### ISSUE TITLE
Make the UI more optimistic 

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#16]
When you submit an transaction (create or vote in a poll), the application gives you no feedback. Your input simply disappears.

Instead, we should optimistically make the change locally, perhaps with an indication that the change is pending confirmation until it is confirmed on chain.

**Comment by samgos** [comment]
Introduced an alert system for transaction updates in https://github.com/burnsignal/burnsignal/commit/1ba94c21370e732b3e17179e75c8b13638517423 and substitute data when broadcasting transactions in https://github.com/burnsignal/burnsignal/commit/da952ff870714700763a896d10509dc6d10a30e2.
