### ISSUE TITLE
Recheck verification after user comes back from bright ethereum

### ISSUE THREAD

**Issue by adamstallard** [burnsignal/burnsignal#18]
Luke had to refresh after coming back from Bright Ethereum to be able to see that the logo was orange and he was now verified.  Before he refreshed, it offered to have him "sign in" again and tried to send him back to Bright Ethereum.

We should be able to detect if someone left to go to Bright Ethereum and then our tab regains focus. On the focus event, we should check `/verifications` again--possibly several times in a loop.

**Comment by auryn-macmillan** [comment]
Closing this issue because #20 makes it redundant.
