### ISSUE TITLE
Add markdown

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#19]
It would be great if we could format the descriptions of polls using Markdown.

We should probably restrict formatting to **Bold**, _Italic_, `mono`, and [link](), for the time being.

**Comment by samgos** [comment]
Integrated in https://github.com/burnsignal/burnsignal/commit/c0dc7a6a2a016fb7ffe326e9c2f5932055455c76 by implementing the library [react-markdown](https://github.com/rexxars/react-markdown).
