### ISSUE TITLE
Add Bright-Ethereum functionality to any app

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#20]
It is a poor user experience for us to send users to Bright-Ethereum to link their ethereum address to BrightID.
We should move this functionality to inside of the dapp.

Users should be able to:
1. Link their address
2. Claim a sponsorship
3. See their progress (whether or not they are linked, sponsored, and verified)

**Comment by adamstallard** [comment]
If we do this right, we can create a generic package that anyone can install for their frontend and point to their own smart contract for their context that emit sponsor events (or by default use the "ethereum" context).

**Comment by adamstallard** [comment]
Let's aim for package that creates a modal UI that can be dropped into any application.  [Web3 modal](https://github.com/Web3Modal/web3modal) is an inspiration for this appraoach.
