### ISSUE TITLE
Make BrightID connections natively in the dapp

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#3]
BrightID is working on an feature that will allow us to make connections natively within our dapp, so users will not need to interact with the BrightID app to make connections. We should implement this ASAP as it will drastically improve our UX.

**Comment by adamstallard** [comment]
This is a planned feature, but it's [5 months out](https://docs.google.com/document/d/1CEBWv4ImXsZYQ2Qll7BXojeKI9CGtzRXjB9aFIj00c4/edit#).  We haven't started working on it yet.

**Comment by auryn-macmillan** [comment]
Yeah, I know. Just figured I'd throw it in the backlog while I was thinking about it. Can't wait for this feature to go live though!

**Comment by Tomasvrba** [comment]
@auryn-macmillan I see you updated this and added to the current sprint. AFAIK this is not yet a feature in BrightID or is this live @adamstallard?
Right now the link still needs to be confirmed in the BrightID app correct?

**Comment by auryn-macmillan** [comment]
My bad, not sure why I added this one. I think I might have confused it for the issue of moving Bright-Ethereum's functionality to inside the app. Looks like we don't have any issue for that. So I'll make one, add it to the sprint, and remove this one.
