### ISSUE TITLE
Dropdown menu is unreadable on mobile

### ISSUE THREAD

**Issue by auryn-macmillan** [burnsignal/burnsignal#9]
On low resolution screens and on mobile devices, the dropdown menu is unreadable.

![burn signal dropdown](https://user-images.githubusercontent.com/8453294/75384972-e94d5500-58ac-11ea-88e3-cea9a2eea0cc.gif)

We should update the styling to be more readable and usable.

**Comment by samgos** [comment]
Resolved for a minimum resolution of 200px in https://github.com/burnsignal/burnsignal/commit/70ea103facb520f4c10d09cf6e4bebcbcf0838f2
